// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDClqqlPEBLR_xN5ifdQdeP5Hub5HiJoU0',
    appId: '1:369174319545:web:204f81d43b0421fdcbe668',
    messagingSenderId: '369174319545',
    projectId: 'heal-a49e3',
    authDomain: 'heal-a49e3.firebaseapp.com',
    storageBucket: 'heal-a49e3.firebasestorage.app',
    measurementId: 'G-2TS9SXK5SK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo5S4sByALJvgtTUpEqsBcQO-3Y5Ji9tk',
    appId: '1:369174319545:android:f89e6df3ba8fc14ecbe668',
    messagingSenderId: '369174319545',
    projectId: 'heal-a49e3',
    storageBucket: 'heal-a49e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgQdk8X5i5WZK8qQwtccv__ijtABkQ-dU',
    appId: '1:369174319545:ios:307f851eecc2c1eecbe668',
    messagingSenderId: '369174319545',
    projectId: 'heal-a49e3',
    storageBucket: 'heal-a49e3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgQdk8X5i5WZK8qQwtccv__ijtABkQ-dU',
    appId: '1:369174319545:ios:307f851eecc2c1eecbe668',
    messagingSenderId: '369174319545',
    projectId: 'heal-a49e3',
    storageBucket: 'heal-a49e3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDClqqlPEBLR_xN5ifdQdeP5Hub5HiJoU0',
    appId: '1:369174319545:web:14d72d26142c1bd8cbe668',
    messagingSenderId: '369174319545',
    projectId: 'heal-a49e3',
    authDomain: 'heal-a49e3.firebaseapp.com',
    storageBucket: 'heal-a49e3.firebasestorage.app',
    measurementId: 'G-FY823LQQ2C',
  );

}